In [1]:
my_list=[1,2,3,4]

In [2]:
import numpy as np

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [22]:
np.linspace(0,5,8)

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429, 5.        ])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(5,5)

array([[0.3123269 , 0.80382905, 0.46762526, 0.55536584, 0.86499508],
       [0.49379583, 0.47920115, 0.06650653, 0.03895509, 0.42625655],
       [0.61671167, 0.13838946, 0.36057579, 0.89017378, 0.97943374],
       [0.38107864, 0.67444065, 0.6625821 , 0.53509475, 0.01456838],
       [0.48222939, 0.49447625, 0.61516487, 0.57288191, 0.68760598]])

In [27]:
np.random.randn(2,2)

array([[-0.1437893 ,  0.05800938],
       [-0.36554376, -1.88646414]])

In [29]:
np.random.randint(1,100,(4,4))

array([[ 5, 36, 99, 28],
       [ 5, 84, 40,  9],
       [60,  5, 17, 44],
       [ 2, 15, 45, 41]])

In [30]:
arr=np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr=np.random.randint(0,50,10)

In [33]:
ranarr

array([16, 26, 22,  5,  7,  3, 41, 33, 44, 28])

In [40]:
wow=arr.reshape(5,5)

In [37]:
ranarr.max()

44

In [38]:
ranarr.argmax()

8

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
wow

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
wow.max()

24

In [46]:
wow.dtype

dtype('int32')

Numpy INDEXING SELECTION

In [47]:
arr=np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr[8]

8

In [50]:
arr[1:5]

array([1, 2, 3, 4])

In [51]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [52]:
arr[0:5]=100

In [53]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [54]:
arr=np.arange(0,11)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
slice_of_arr=arr[0:6]

In [57]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [58]:
slice_of_arr[:]=10

In [59]:
slice_of_arr

array([10, 10, 10, 10, 10, 10])

In [60]:
arr

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [61]:
arr_copy=arr.copy()

In [62]:
arr_copy

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [64]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [65]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr_2d[0][2]

15

In [69]:
arr_2d[0,2]

15

In [72]:
arr_2d[1:3,:2]

array([[20, 25],
       [35, 40]])

In [73]:
arr=np.arange(1,11)

In [74]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
bool_arr=arr > 5

In [77]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [78]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [89]:
n_arr=np.arange(0,50).reshape(5,10)

In [98]:
n_arr[2,3:5]

array([23, 24])

In [95]:
n_arr[2:2]

array([], shape=(0, 10), dtype=int32)

In [99]:
arr= np.arange(0,11)

In [100]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [102]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])